apiVersion: v1
kind: Secret
metadata:
  name: postgres-todo-secret
  namespace: project
type: Opaque
stringData:
  POSTGRES_USER: "todo_user"
  POSTGRES_PASSWORD: "todo_password"
  POSTGRES_DB: "todos_db"