apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

patches:
- path: broadcaster-patch.yaml
- path: remove-backup-cronjob.yaml

images:
- name: TODO-APP/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-app
  newTag: bdfcd16c110ca993e14d0646a5fb803b87d2ff3f
- name: TODO-BACKEND/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-backend
  newTag: bdfcd16c110ca993e14d0646a5fb803b87d2ff3f
- name: flhaka/broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/broadcaster
  newTag: bdfcd16c110ca993e14d0646a5fb803b87d2ff3f
