apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

patches:
- path: broadcaster-patch.yaml
- path: remove-backup-cronjob.yaml

images:
- name: TODO-APP/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-app
  newTag: 9bb5d96f9b4a21b46543bcf269ceb8245fba1ef0
- name: TODO-BACKEND/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/todo-backend
  newTag: 9bb5d96f9b4a21b46543bcf269ceb8245fba1ef0
- name: flhaka/broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-503613/my-repository/broadcaster
  newTag: 9bb5d96f9b4a21b46543bcf269ceb8245fba1ef0
