apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  namespace: exercises
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
  restartPolicy: Always