apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: pingpong:latest
          imagePullPolicy: Never
          env:
          - name: PORT
            value: "3001"
          - name: POSTGRES_HOST
            value: "postgres-svc"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "mydatabase"
          ports:
            - containerPort: 3001