apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-storage-claim
      containers:
        - name: pingpong
          image: pingpong:latest
          imagePullPolicy: Never
          env:
          - name: PORT
            value: "3001"
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
