apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-output
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-config
      containers:
        - name: writer
          image: flhaka/log-output-writer:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-output
              mountPath: /usr/src/app/files
        - name: reader
          image: flhaka/log-output-reader:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-output
              mountPath: /usr/src/app/files
            - name: config-volume
              mountPath: /usr/src/app/config
