apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-output
          emptyDir: {}
      containers:
        - name: writer
          image: log-output-writer:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-output
              mountPath: /usr/src/app/files
        - name: reader
          image: log-output-reader:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-output
              mountPath: /usr/src/app/files