apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: TODO-APP/IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_URL
            - name: IMAGE_CACHE_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_CACHE_MINUTES
            - name: TODO_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: TODO_BACKEND
            - name: IMAGE_DIR
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_DIR
          volumeMounts:
            - name: todo-storage
              mountPath: /usr/src/app/files
