name: Release application

on:
  push:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: GKE_PROJECT

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v3

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Configure Docker for Artifact Registry'
        run: gcloud --quiet auth configure-docker $REGISTRY

      - name: 'Get GKE credentials'
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: 'Form the image name'
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and push todo-app
        run: |
          cd the_project/todo-app
          IMAGE_TAG="$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:$BRANCH-$GITHUB_SHA"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "TODO_APP_IMAGE=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and push todo-backend
        run: |
          cd the_project/todo-backend
          IMAGE_TAG="$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$BRANCH-$GITHUB_SHA"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "TODO_BACKEND_IMAGE=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Deploy
        run: |-
          cd the_project
          kustomize edit set image TODO-APP/IMAGE=${{ env.TODO_APP_IMAGE }}
          kustomize edit set image TODO-BACKEND/IMAGE=${{ env.TODO_BACKEND_IMAGE }}
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/todo-app -n project
          kubectl rollout status deployment/todo-backend -n project
          kubectl get pods -n project
          kubectl get services -n project
